In [2]:
import sklearn
import numpy as np
import scipy as sp
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
coffea_orig = pd.read_csv(r"..\input\project_input_nonbin.csv")

In [4]:
coffea_orig.describe()

,source_crs,longitude,latitude,sampled_layers,nodata_layers,tmin1,tmin2,tmin3,tmin4,tmin5,...,ndm_year,altitude,slope,aspect,solrad,rock_types,soil_types,veg_types,watersheds,forest_coverage
count,189.0,189.000000,189.000000,189.0,189.000000,188.000000,188.000000,188.000000,188.000000,188.000000,...,188.000000,187.000000,186.000000,186.000000,186.000000,183.000000,187.000000,188.000000,188.000000,187.000000
mean,4326.0,48.658536,-15.003286,79.0,0.492063,168.148936,195.585106,194.787234,187.914894,169.659574,...,6.345745,626.053476,9.564516,162.747312,7814.360215,8.633880,11.620321,10.489362,8.712766,63.588235
std,0.0,1.128089,4.357381,0.0,5.765469,27.834291,25.327126,25.251197,25.187281,26.873462,...,2.225913,472.608715,6.870118,103.901542,366.973560,1.607793,5.586102,4.414959,4.646020,38.908584
min,4326.0,44.732222,-24.842778,79.0,0.000000,83.000000,123.000000,122.000000,114.000000,93.000000,...,1.000000,0.000000,0.000000,4.000000,6475.000000,2.000000,4.000000,2.000000,1.000000,0.000000
25%,4326.0,49.065830,-14.221940,79.0,0.000000,144.000000,170.000000,171.000000,167.000000,153.000000,...,6.000000,142.000000,4.000000,58.000000,7706.000000,9.000000,8.000000,6.750000,5.000000,21.000000
50%,4326.0,49.150000,-12.846388,79.0,0.000000,167.000000,194.500000,193.000000,187.500000,166.000000,...,7.000000,582.000000,8.000000,172.000000,7908.500000,9.000000,8.000000,14.000000,12.000000,72.000000
75%,4326.0,49.174722,-12.530000,79.0,0.000000,190.000000,216.000000,213.000000,209.000000,185.500000,...,8.000000,1079.000000,13.000000,243.000000,8040.000000,9.000000,18.000000,14.000000,12.000000,100.000000
max,4326.0,49.985833,-12.310000,79.0,79.000000,224.000000,241.000000,242.000000,240.000000,232.000000,...,10.000000,1782.000000,30.000000,358.000000,8353.000000,10.000000,22.000000,25.000000,14.000000,100.000000

In [5]:
coffea_orig.shape

(189, 89)

In [6]:
coffea = coffea_orig.copy()
coffea.drop(columns=['source_crs', 'mada_geom_point', 'sampled_layers', 'nodata_layers', 'is_categorical_encoded', 'genus', 'species'],inplace=True)

In [7]:
coffea

,specimen_id,longitude,latitude,tmin1,tmin2,tmin3,tmin4,tmin5,tmin6,tmin7,...,ndm_year,altitude,slope,aspect,solrad,rock_types,soil_types,veg_types,watersheds,forest_coverage
0,spe1_duba,49.213056,-12.479722,175.0,199.0,200.0,196.0,183.0,166.0,161.0,...,8.0,582.0,6.0,12.0,8169.0,9.0,8.0,7.0,1.0,34.0
1,spe1_auga,49.213056,-12.479722,175.0,199.0,200.0,196.0,183.0,166.0,161.0,...,8.0,582.0,6.0,12.0,8169.0,9.0,8.0,7.0,1.0,34.0
2,spe1_moge,49.166389,-12.524444,144.0,170.0,171.0,167.0,153.0,135.0,132.0,...,7.0,1079.0,13.0,58.0,8192.0,9.0,8.0,14.0,12.0,100.0
3,spe2_auga,49.213056,-12.479722,175.0,199.0,200.0,196.0,183.0,166.0,161.0,...,8.0,582.0,6.0,12.0,8169.0,9.0,8.0,7.0,1.0,34.0
4,spe2_duba,49.083333,-12.900000,208.0,227.0,229.0,225.0,211.0,191.0,184.0,...,8.0,165.0,28.0,358.0,7892.0,7.0,22.0,5.0,13.0,12.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184,spe65_moge,49.180000,-12.530000,145.0,173.0,173.0,169.0,155.0,138.0,134.0,...,7.0,1095.0,4.0,10.0,8252.0,9.0,8.0,14.0,12.0,100.0
185,spe66_moge,49.180000,-12.530000,145.0,173.0,173.0,169.0,155.0,138.0,134.0,...,7.0,1095.0,4.0,10.0,8252.0,9.0,8.0,14.0,12.0,100.0
186,spe76_duba,49.700000,-13.180000,200.0,225.0,222.0,219.0,204.0,185.0,181.0,...,8.0,171.0,8.0,36.0,7888.0,10.0,9.0,6.0,1.0,24.0
187,spe77_duba,49.700000,-13.180000,200.0,225.0,222.0,219.0,204.0,185.0,181.0,...,8.0,171.0,8.0,36.0,7888.0,10.0,9.0,6.0,1.0,24.0
188,spe67_moge,49.166670,-12.516670,147.0,173.0,173.0,170.0,156.0,139.0,134.0,...,7.0,1032.0,4.0,171.0,8103.0,9.0,8.0,14.0,12.0,100.0